= Char! - typ danych
Version: Draft 3
:toc:
:numbered:

== Streszczenie

Wartości `char!` reprezentują współrzędne kodowania Unicode. Są liczbami całkowitymi z zakresu szesnastkowego 00 do szesnastkowego 10FFFF. (0 do 1,114,111 w dziesiętnym systemie.)

`Char!` jest członkiem danych typesetów (zbiór typów): `immediate!`, `scalar!`

== Własności

Wartości 'Char!' są 'bezpośrednie', 'atomistyczne' i 'pasywne'.

NOTE: To zakłada, że Własności Typów jest już zdefiniowane w tym dokumencie.

== Tworzenie

Wartości `Char!` mogą być stworzone przez dosłowną składnie albo w trakcie wykonywania przez użycie konstruktora `make`, konwertera `to` albo wielu funkcji, które działają na wartościach `string!`, aby wydobyć wartość `char!`.

=== Dosłowna składnia

Podstawowym dosłownym formatem dla `char!` jest:

----
#"<znak>"
<znak> : pojedyncze współrzędne kodowania Unicode (zwykle wprowadzone przez naciśnięcie klawisza)
----

Dosłowna składnia dopuszcza znaki ucieczki/modyfikacji dla znaków kontrolnych albo tych znaków, które nie można łatwo wprowadzić.

Znak ucieczki w Red to '^' - współrzędne kodowania U+005E. Ze względu na użycie '^', musimy użyć znaku ucieczki. Poprawne użycie: #"^^". #"^" jest niepoprawne.

Są trzy formy modyfikacji znaków w Red (numeryczne współrzędne kodowania, nazwane znaki i znaki kontrolne).

Współrzędne kodowania - składnia:

----
#"^(<współrzędne kodowania>)"
<współrzędne kodowania> : wartość szesnastkowa, np. 00, ABCD, 10FFFFF
----

Znaki kontrolne - składnia:

----
#"^<cc>"
<cc> : Pojedynczy znak ze zbioru: - A-Z, [, \, ], _
----

.Znaki kontrolne
[cols="2*"]
|===

|Znak
|Współrzędna kodowania

|#"^A" - #"^Z"
|U+0001 - U+001A.

|#"^["
|U+001B

|#"^\"
|U+001C

|#"^]"
|U+001D

|#"^_"
|U+001F

|===

Nazwane znaki - składnia:

----
#"^(<nazwa>)" albo #"^<symbol>"
<nazwa> : nazwa z tabeli "Nazwane znaki modyfikacji"
<symbol> : symbol z tabeli "Nazwane znaki modyfikacji"
----

.Nazwane znaki modyfikacji
[cols="4*"]
|===

|nazwa
|symbol
|znak
|współrzędne kodowania

|#"^(null)
|#"^@"
|null
|U+0000

|#"^(back)"
|
|backspace
|U+0008

|#"^(tab)"
|#"^-"
|horizontal tab
|U+0009

|#"^(line)"
|#"^/"
|line feed
|U+000A

|#"^(page)"
|
|form feed
|U+000C

|#"^(esc)"
|
|escape
|U+001B

|#"^(del)"
|#"^~"
|delete
|U+007F

|
|#"^""
|" - double quote
|U+0022

|
|#"^^"
|^ - caret
|U+005E

|===


== Porównania

Wszystkie operatory porównań mogą być użyte z `char!': `=, ==, <>, >, <, >=, &lt;=, =?`. Ponadto, `min`, `max` i `sort` też są wspierane. Porównania `char!` są rozróżniane ze względu na wielkość liter.

*Przykłady*

----
#"a" = #"A"
== false
#"a" =? #"a"
== true
max #"a" #"A"
== #"a"
sort [#"c" #"b" #"d" #"a"]
== [#"a" #"b" #"c" #"d"]
----


== Arytmetyka
Pełny zakres matematycznych funkcji może być użyte z `char!`. Błąd `Math Error` będzie podniesiony jeżeli wartości nie będzie z zakresu 00 - 10FFFF (szesnastkowe).

*Przykłady*

```red
>> #"a" + 1
== #"b"

>> #"a" - 32
== #"A"

>> #"a" * 256
== #"愀"

>> #"a" - 98
*** Math Error: math or number overflow
*** Where: -
*** Stack:
```
[NOTE]
Wynik operacji matematycznych będzie przekształcony do typu pierwszego argumentu.

```red
>> #"a" + 1
== #"b"

>> 1 + #"a"
== 98

>> #"a" - 32
== #"A"

>> 32 - #"a"
== -65

>> 256.00 * #"a"
== 24832.0
```

== Uprzednio zdefiniowane słowa

----
null             #"^@"
newline          #"^/"
slash            #"/"
dbl-quote        #"^""
space            #" "
lf               #"^/"
tab              #"^-"
CR               #"^M"
dot              #"."
escape           #"^["
sp               #" "
comma            #","
----

== Inne funkcje związane z `char!`

Lowercase, Uppercase
