= Date! - typ danych
:toc:
:numbered:

== Streszczenie

Wartości `date!` reprezentują kalendarzową date, używając Gregorjańskiego kalendarza. Wartość `date!` mogą też zawierać opcjonalny czas i strefę czasową. Czas jest wyrażony w 24 godzinnym formacie (łącznie z opcjonalną strefą czasową). Wartości `date!` Red też rozlegle wspierają format https://en.wikipedia.org/wiki/ISO_8601[ISO 8601].

[NOTE]
====
* `date!` używa https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar[proleptic Gregorian calendar], rozszerzając go wstecz ponad rok 1582. Trzeba uważać, gdy chcemy reprezentować historyczne, przed Gregoriańskie, daty używając wartości `date!`.

* Wspierany zakres dat to `1/Jan/-16384` do `31/Dec/16383`, wracając spowrotem w wypadku przepełnienia operacji matematycznych. W czasie wpisywania ten zakres jest zmniejszony do zakresu od `1/Jan/-9999` do `31/Dec/9999` dla praktycznych przyczyn.
====


== Tworzenie

Wartości `date!` mogą być stworzone przy użyciu dosłownej składni, albo podczas wykonywania przy użyciu konstruktora `make` lub konwertera `to`.


=== Dosłowna składnia

Wiele formatów jest wspierana, włączając wszystkie formaty Rebol i większość formatów ze standardu ISO.

----
<date>/<time>
<date>/<time><zone>
<date>T<time>
<date>T<time>Z
<date>T<time><zone>

<date> formats:
    <yyyy><sep><mmm><sep><dd>
    <dd><sep><mmm><sep><yyyy>
    <dd><sep><mmm><sep><yy>

Additional <date> formats when followed by T:
    <yyyy><mm><dd>
    <yyyy>-W<ww>
    <yyyy>-W<ww>-<d>
    <yyyy>-<ddd>

<mmm> formats (month):
    <m>
    <mon>
    <month>

<time> formats:
    <hour>:<min>:<sec>
    <hour>:<min>:<sec><zone>
    <hhmmss>
    <hhmmss><zone>
    <hhmmss>.<dec>
    <hhmmss>.<dec><zone>
    <hhmm>
    <hhmm><zone>

<zone> formats (timezone):
    <sign><hour>
    <sign><hour>:<min15>
    <sign><hhmm>

<sec> formats (seconds):
    <ss>
    <ss>.<dec>

<sep>    : `-` or `/`
<yyyy>   : 3 albo 4 cyfry reprezentujące rok (4 cyfry dla dat ISO)
<yy>     : 2 cyfry reprezentujące rok w stosunku do 2000 roku
<m>      : 1 albo 2 cyfry reprezentujące miesiąc
<mm>     : 2 cyfry reprezentujące miesiąc
<mon>	 : 3 znaki reprezentujące początek miesiąca
<month>  : pełna nazwa miesiąca
<d>      : cyfra reprezentująca dzień tygodnia (od 1 do 7)
<dd>     : 1 albo 2 cyfry reprezentujące dzień miesiąca
<ddd>    : 3 cyfry reprezentujące dzień roku
<ww>     : 2 cyfry reprezentujące tydzień roku
<time>   : wartość time!
<hour>   : 1 albo 2 cyfry reprezentujące godziny
<min>    : 1 albo 2 cyfry reprezentujące minuty
<ss>     : 1 albo 2 cyfry reprezentujące sekundy
<dec>    : wartość dziesiętna dla sekund
<sign>   : znak `+` albo `-` (nie mozna go pominąć)
<min15>  : takie same jak <min>, ale zaokrąglone do wielokrotności 15.
<hhmm>   : 4 cyfry dla godzin i minut (bez separatora)
<hhmmss> : 6 cyfr dla godzin, minut i sekund (bez separatora)
----

Wiele różnych formatów wprowadzania jest akceptowana. Wartości poza zakresem (przekraczając specyficzne numer albo wzorzec pola) wywołają błąd syntaktyki. W przypadku serializowania (np. dla wyświetlenia), tylko niżej wymienione kanoniczne formaty są użyte:

----
<dd>-<mon>-<yyyy>
<dd>-<mon>-<yyyy>/<hour>:<min>:<sec>
<dd>-<mon>-<yyyy>/<hour>:<min>:<sec><sign><hour>:<min15>
----

Kiedy czas i/albo strefa czasowa nie jest ustawiona, są one pomijane. Dla ujemnych dat, separator `/` jest użyty zamiast `-` dla większej czytelności.

[NOTE]
====
* Kiedy miesiąc jest zapisany używając liter, wtedy muszą być użyte angielskie nazyw, nie zważając na wielkość liter.
* Kiedy rok jest zapisany przy użyciu 2 cyfr (`yy`): jeżeli jest < 50, jest interpretowany jako `20yy`, w innych przypadkach jest interpretowany jako `19yy`.
====

Przykłady poprawnie wprowadzonych dat:

----
1999-10-5
1999/10/5
5-10-1999
5/10/1999
5-October-1999
1999-9-11
11-9-1999
5/sep/2012
5-SEPTEMBER-2012

02/03/04
02/03/71

5/9/2012/6:0
5/9/2012/6:00
5/9/2012/6:00+8
5/9/2012/6:0+0430
4/Apr/2000/6:00+8:00
1999-10-2/2:00-4:30
1/1/1990/12:20:25-6

2017-07-07T08:22:23+00:00
2017-07-07T08:22:23Z
20170707T082223Z
20170707T0822Z
20170707T082223+0530

2017-W01
2017-W23-5
2017-W23-5T10:50Z
2017-001
2017-153T10:50:00-4:00
----


=== Tworzenie w czasie wykonywania

----
make date! [<day> <month> <year>]
make date! [<year> <month> <day>]
make date! [<day> <month> <year> <time>]
make date! [<day> <month> <year> <time> <zone>]
make date! [<day> <month> <year> <hour> <minute> <second>]
make date! [<day> <month> <year> <hour> <minute> <second> <zone>]

<year>   : integer! value
<month>  : integer! value
<day>    : integer! value
<time>   : time! value
<zone>   : integer!, time! or pair! value
<hour>   : integer! value
<minute> : integer! value
<second> : integer! value
----

[NOTE]
====
* Argument poza zakresem zwróci błąd. Dla znormalizowanych wartości, użyj akcji `to` zamiast `make`.

* Pola `year` i `day` są zamienne, ale tylko dla niskich wartości roku.

Używając `make`, rok moze być użyty na pierwszej pozycji *tylko* jeżeli jej wartość jest >= 100.

Używając `to`, pierwsza pozycja może być użyta dla roku (`year`) *tylko* jeżeli jej wartość jest >= 100 i jej wartość jest większa od wartość trzeciego pola. Jeżeli ta reguła nie spełniona, wtedy trzecie pole będzie potraktowane jako rok (`year`).

Ujemne lata zawsze powinny być wymienione na trzeciej pozycji
====

*Przykłady*

----
make date! [1978 2 3]
== 3-Feb-1978

make date! [1978 2 3 5:0:0 8]
== 3-Feb-1978/5:00:00+08:00

make date! [1978 2 3 5:0:0]
== 3-Feb-1978/5:00:00

make date! [1978 2 3 5 20 30]
== 3-Feb-1978/5:20:30

make date! [1978 2 3 5 20 30 -4]
== 3-Feb-1978/5:20:30-4:00


make date! [100 12 31]
== 31-Dec-0100

; 32 nie jest prawidłowym dniem
make date! [100 12 32]
*** Script Error: cannot MAKE/TO date! from: [100 12 32]
*** Where: make

; Pierwsze pole jest < 100, więc nie jest interpretowane jako rok
make date! [99 12 31]
*** Script Error: cannot MAKE/TO date! from: [99 12 31]
*** Where: make
----

* Używając konwertera `to` (zobacz 4.1 <<_epoch_time>>).

----
to-integer <date>
to-date <epoch>

<date>  : a date! value
<epoch> : an integer value representing an epoch time
----

== Akcesory ścieżki

Akcesory ścieżki zapewniają dogodny sposób na pobieranie i ustawianie wszystkich pól wartości `date!`.

=== /date

*Syntaktyka*

----
<date>/date
<date>/date: <date2>

<date>  : wartości `word!` albo `path!` odnoszące się do wartości `date!`
<date2> : wartość `date!`
----

*Opis*

Pobiera albo ustawia pole daty (wyłączając czas i strefę). Daty są zwracane jako wartości `date!`

*Przykłady*

----
d:  now
== 10-Jul-2017/22:46:22-06:00
d/date
== 10-Jul-2017

d/date: 15/09/2017
== 15-Sep-2017/22:46:22-06:00
----


=== /year

*Syntaktyka*

----
<date>/year
<date>/year: <year>

<date> : wartości `word!` albo `path!` odnoszące się do wartości `date!`
<year> : wartość `integer!`
----

*Opis*

Pobiera albo ustawia pole roku. Lata są zwracane jako wartość `integer!`. Argumenty poza zakresem spowodują normalizacje daty.

*Przykłady*

----
d:  now
== 10-Jul-2017/22:46:22-06:00
d/year: 16383
== 16383
d
== 10-Jul-16383/22:46:22-06:00
d/year: 16384
== 16384
d
== 10/Jul/-16384/22:46:22-06:00     ; wartość wraca po roku 16384
d/year: 32767
== 32767
d
== 10/Jul/-1/22:46:22-06:00
d/year: 32768
== 32768
d
== 10-Jul-0000/22:46:22-06:00
----


=== /month

*Syntaktyka*

----
<date>/month
<date>/month: <month>

<date>  : wartości `word!` albo `path!` odnoszące się do wartości `date!`
<month> : wartość `integer!`
----

*Opis*

Pobiera albo ustawia pole miesiąca. Miesiące są zwracane jako wartości `integer!`. Wartości poza zakresem spowodują normalizacje daty.

*Przykłady*

----
d: now
== 10-Jul-2017/22:48:31-06:00
d/month: 12
== 12
d
== 10-Dec-2017/22:48:31-06:00
d/month: 13
== 13
d
== 10-Jan-2018/22:48:31-06:00   ; przejście do następnego roku
d/month
== 1                            ; Miesiąc jest znormalizowan
----


=== /day

*Syntaktyka*

----
<date>/day
<date>/day: <day>

<date> : wartości `word!` albo `path!` odnoszące się do wartości `date!`
<day>  : wartość `integer!`
----

*Opis*

Pobiera albo ustawia pole dnia. Dni są zwracane jako wartości `integer!`. Wartości poza zakresem spowodują normalizacje daty.

*Przykłady*

----
 d: 1-jan-2017
== 1-Jan-2017
d/day: 32
== 32
d
== 1-Feb-2017
d/day: 0         ; Sprawdź jak działa 0 dla poprawnej matematyki dat
== 0
d
== 31-Jan-2017
----


=== /time

*Syntaktyka*

----
<date>/time
<date>/time: <time>

<date> : wartości `word!` albo `path!` odnoszące się do wartości `date!`
<time> : wartość `time!` albo `none!`
----

*Opis*

Pobiera albo ustawia pole czasu. Czas jest zwracany jako wartość `time!` albo wartość `none!` jeżeli czas nie jest ustawiony lub został zresetowany (popatrz niżej). Wartości poza zakresem spowodują normalizacje daty.

Jeżeli czas zostanie ustawiony do wartości `none!` wtedy pola czasu i strefy są ustawione na zero i nie są pokazywane.

*Przykłady*

----
d: now
== 10-Jul-2017/23:18:54-06:00
d/time: 1:2:3
== 1:02:03
d
== 10-Jul-2017/1:02:03-06:00
d/time: none
== 10-Jul-2017
----


=== /hour

*Syntaktyka*

----
<date>/hour
<date>/hour: <hour>

<date> : wartości `word!` albo `path!` odnoszące się do wartości `date!`
<hour> : wartość `integer!`
----

*Opis*

Pobiera albo ustawia pole godziny. Godziny są zwracane jako wartości `integer!` z zakresu od 0 do 23. Wartości poza zakresem spowodują normalizacje daty.

*Przykłady*

----
d: now
== 10-Jul-2017/23:19:40-06:00
d/hour: 0
== 0
d
== 10-Jul-2017/0:19:40-06:00
d/hour: 24
== 24
d
== 11-Jul-2017/0:19:40-06:00
----


=== /minute

*Syntaktyka*

----
<date>/minute
<date>/minute: <minute>

<date>   : wartości `word!` albo `path!` odnoszące się do wartości `date!`
<minute> : wartość `integer!`
----

*Opis*

Pobiera albo ustawia pole minuty. Minuty są zwracane jako wartość `integer!` z zakresu od 0 do 50. Wartości poza zakresem spowodują normalizacje daty.

*Przykłady*

----
== 10-Jul-2017/23:20:25-06:00
d/minute: 0
== 0
d
== 10-Jul-2017/23:00:25-06:00
d/minute: 60
== 60
d
== 11-Jul-2017/0:00:25-06:00
----


=== /second

*Syntaktyka*

----
<date>/second
<date>/second: <second>

<date>   : wartości `word!` albo `path!` odnoszące się do wartości `date!`
<second> : wartość `integer!` albo `float!`
----

*Opis*

Pobiera albo ustawia pole sekundy. Sekundy są zwracane jako wartość `integer!` albo `float!` zakresu od 0 do 59. Wartości poza zakresem spowodują normalizacje daty.

*Przykłady*

----
d: now
== 10-Jul-2017/23:21:15-06:00
d/second: 0
== 0
d
== 10-Jul-2017/23:21:00-06:00
d/second: -1
== -1
d
== 10-Jul-2017/23:20:59-06:00
d/second: 60
== 60
d
== 10-Jul-2017/23:21:00-06:00
----


=== /zone

*Syntaktyka*

----
<date>/zone
<date>/zone: <zone>

<date> : wartości `word!` albo `path!` odnoszące się do wartości `date!`
<zone> : wartość `time!` albo `integer!`
----

*Opis*

Pobiera albo ustawia pole strefy czasowej. Strefy czasowe są zwracane jako wartośći `time!` z zakresu od -16:00 do +15:00. Ustawianie strefy czasowej przy użyciu `/zone` zmieni tylko to pole, czas będzie taki sam. Wartości poza zakresem spowodują normalizacje daty.

Kiedy strefa czasowa jest wyrażona jako wartość `integer!`, wtedy reprezentuje ona godziny, a minuty są ustawione na 0.

Ziarnistość minut strefy czasowej jest ustawiona na 15, inne wartość będą zaokrąglone w dół do wielokrotności 15 minut.

*Przykłady*

----
d: 1/3/2017/5:30:0
d/zone: 8
== 1-Mar-2017/5:30:00+08:00

d/zone: -4:00
== 1-Mar-2017/5:30:00-04:00
----

[NOTE]
Ustawienie wartości `/zone` do wartości `date!` bez pola `time` zwróci wartość `date!` z polem `time` ustawionym domyślnnie do 0:0:0.

*Przykłady*

----
d: 28-Mar-2019
== 28-Mar-2019

d/zone: 1 d
== 28-Mar-2019/0:00:00+01:00
----

=== /timezone

*Syntaktyka*

----
<date>/timezone
<date>/timezone: <timezone>

<date>     : wartości `word!` albo `path!` odnoszące się do wartości `date!`
<timezone> : wartość `integer!` albo `time!`
----

*Opis*

Pobiera albo ustawia pole strefy czasowej. Strefy czasowe sa zwrócane jako wartość `time!` z zakresu od -16:00 do +15:00. Ustawienie strefy czsaowej przy użyciu  `/timezone` zmodyfikuje czas i strefę, utrzymując nowy czasy takim samym w stosunku do starego czasu. Wartości poza zakresem spowodują normalizacje daty.

Kiedy strefa czasowa jest ustawiona przy użyciu wartości `integer!`, wtedy reprezentuje ona godziny, a minuty są ustawione na 0.

Ziarnistość minut strefy czasowej jest ustawiona na 15, inne wartość będą zaokrąglone w dół do wielokrotności 15 minut.

*Przykłady*

----
d: 1/3/2017/5:30:0
d/timezone: 8
== 1-Mar-2017/13:30:00+08:00

d/timezone: -4:00
== 1-Mar-2017/1:30:00-04:00
----

[NOTE]
====
* Ustawienie `/timezone` na 0 spowoduje ustawienie czasu do UTC.
====


=== /yearday

*Syntaktyka*

----
<date>/yearday
<date>/yearday: <day>

<date>    : wartości `word!` albo `path!` odnoszące się do wartości `date!`
<yearday> : wartość `integer!`
----

*Opis*

Pobiera dzień roku, zaczynając od 1 dla pierwszego stycznia. Dni są zwracane jako wartości `integer!`. Kiedy są użyte dla ustawienie dnia roku, wtedy data jest ponownie obliczona, aby dopasować się do danego dnia. Wartości poza zakresem spowodują normalizacje daty.

Nota:

* alias `/julian` dla `/yearday` też jest wspierany dla kompatybilności z Rebol.

*Przykłady*

----
d: 1-jan-2017
== 1-Jan-2017
d/yearday
== 1
d: 31-dec-2017
== 31-Dec-2017
d/yearday
== 365
d: 31-dec-2020
== 31-Dec-2020
d/yearday
== 366                  ; Rok przestępny

d: 31-dec-2017
== 31-Dec-2017
d/yearday: 366
== 366
d
== 1-Jan-2018
----


=== /weekday

*Syntaktyka*

----
<date>/weekday
<date>/weekday: <day>

<date>    : wartości `word!` albo `path!` odnoszące się do wartości `date!`
<weekday> : wartość `integer!`
----

*Opis*

Pobiera dzień tygodnia, 1 dla poniedziałku kończąc na 7 dla niedzieli. Kiedy jest użyte dla ustawienia dnia tygodnia, wtedy data jest ponownie obliczona, aby dopasować się danego dnia. Wartości poza zakresem spowodują normalizacje daty.

*Przykłady*

----
d: now
== 10-Jul-2017/23:25:35-06:00
d/weekday
== 1
d/weekday: 2
== 2
d
== 11-Jul-2017/23:25:35-06:00
d/weekday: 7
== 7
d
== 16-Jul-2017/23:25:35-06:00
d/weekday: 8
== 8
d
== 17-Jul-2017/23:25:35-06:00
----


=== /week

*Syntaktyka*

----
<date>/week
<date>/week: <day>

<date> : wartości `word!` albo `path!` odnoszące się do wartości `date!`
<week> : wartość `integer!`
----

*Opis*

Pobiera numer tygodnia używając pospolitej definicji (tydzień zaczyna się w niedzielę; pierwszy tydzień zaczyna się 1 stycznia), z zakresu 1 (dla pierwszego tygodnia roku) kończąc na 53. Kiedy jest użyty do ustawienia numeru tygodnia, wtedy data jest ponownie obliczona, aby dopasować się do pierwszego dnia tego tygodnia (niedziela). Wartości poza zakresem spowodują normalizacje daty.

[NOTE]
====
* Pospolita definicja tygodnia pozwala, aby pierwszy i ostatni tydzień roku był niepełny (od 1 do 7 dni). Dla bardziej precyzyjnych obliczeń przez lata użyj akcesora `/isoweek`.
====

*Przykłady*

----
d: now
== 10-Jul-2017/23:28:07-06:00
d/week
== 28
d/week: 29
== 29
d
== 16-Jul-2017/23:28:07-06:00
d/week: 52
== 52
d
== 24-Dec-2017/23:28:07-06:00
d/week: 53
== 53
d
== 31-Dec-2017/23:28:07-06:00
d/week: 54
== 54
d
== 7-Jan-2018/23:28:07-06:00
----


=== /isoweek

*Syntaktyka*

----
<date>/isoweek
<date>/isoweek: <day>

<date>    : wartości `word!` albo `path!` odnoszące się do wartości `date!`
<isoweek> : wartość `integer!`
----

*Opis*

Pobiera numer tygodnia przy użyciu definicji https://en.wikipedia.org/wiki/ISO_week_date[ISO 8601], z zakresu 1 (dla pierwszego tygodnia roku) do 52(albo 53 dla niektórych lat). Kiedy jest użyty do ustawienia numeru tygodnia, wtedy data jest ponownie obliczona, aby dopasować się do pierwszego dnia tego tygodnia (poniedziałek). Wartości poza zakresem spowodują normalizacje daty.

*Przykłady*
----
d: now
== 10-Jul-2017/23:29:13-06:00
d/isoweek
== 28
d/isoweek: 29
== 29
d
== 17-Jul-2017/23:29:13-06:00
d/isoweek: 52
== 52
d
== 25-Dec-2017/23:29:13-06:00
d/isoweek: 53
== 53
d
== 1-Jan-2018/23:29:13-06:00
----


=== Porządkowe akcesory

Oprócz użycia słów do pobierania wartości pól, możliwe też jest użycie liczbowego indeksu w wyrażeniu ścieżki

----
<date>/<index>

<date>  :wartości `word!` albo `path!` odnoszące się do wartości `date!`
<index> : wartość  `integer!` odnosząca się do pola czasu.
----

Takie porządkowe akcesory mogą być użyte do pobierania albo ustawiania pól. Poniższa tabela przedstawia odpowiedniki

[cols="1,1",options="header",align="center"]
|===
|Indeks | Nazwa
| 1| date
| 2| year
| 3| month
| 4| day
| 5| zone
| 6| time
| 7| hour
| 8| minute
| 9| second
|10| weekday
|11| yearday
|12| timezone
|13| week
|14| isoweek
|===


=== Uzyskiwanie dostępu do pól przy użyciu Pick

Możliwe jest dostęp do pól bez użycia ścieżki, co może być bardziej dogodne w niektórych przypadkach. `pick` może być użyte na wartościach `date!`.

*Syntaktyka*

----
pick <date> <field>

<date>  : wartość `date!`
<field> : wartość `integer!`
----

Argument reprezentuje porządkowy akcesor dla dat. Zobacz tabela "Porządkowe akcesory" powyżej.

*Przykłady*

----
d: now
== 10-Jul-2017/23:35:01-06:00
names: system/catalog/accessors/date!
repeat i 14 [print [pad i 4 pad names/:i 10 pick d i]]
1    date       11-Jul-2017
2    year       2017
3    month      7
4    day        11
5    zone       8:00:00
6    time       21:43:52
7    hour       21
8    minute     43
9    second     52.0
10   weekday    2
11   yearday    192
12   timezone   8:00:00
13   week       28
14   isoweek    28
----


== Konwersja

=== Czas epoki

Wartości `date!` mogą być konwertowane z/do https://en.wikipedia.org/wiki/Unix_time[Unix epoch time] przy użyciu akcji `to`.

*Syntaktyka*

----
to-integer <date>
to-date <epoch>

<date>  : wartość `date!`
<epoch> : wartość `integer` reprezentująca czas epoki
----

Czas epoki jest wyrażony w UTC. Jeżeli argument nie jest w UTC, wtedy będzie on skonwertowany wewnętrznie przed konwersją do czasu epoki

----
d: 8-Jul-2017/17:49:27+08:00
to-integer d
== 1499507367

to-integer 8-Jul-2017/9:49:27
== 1499507367

to-date to-integer d
== 8-Jul-2017/9:49:27
----

Zauważ, że czas epoki nie jest zdefiniowany dla roku powyżej 2038


=== `block!` do `date!`

*Syntaktyka*

----
to date! <spec>

<spec> : wartość `block!` zawierająca wartości dla pól
----

Argument `block!` będzie skonwertowany do wartości `date!` używając tej samej syntaktyki jak dla `make` (zobacz 2.2 <<_Tworzenie_w_czasie_wykonywania>>). Wartości poza zakresem spowodują normalizacje daty. Dla surowszych konwersji, które spowodują błąd zamiast normalizacji, użyj `make`.


== Porównania

Wszystkie operatory porównań mogą być użyte z `date!`: `=, ==, <>, >, <, >=, &lt;=, =?`. Ponadto `min`, `max` i `sort` też są wspierane.

*Przykłady*

----
3-Jul-2017/9:41:40+2:00 = 3-Jul-2017/5:41:40-2:00
== true

10/10/2017 < 1/1/2017
== false

max 10/10/2017 1/1/2017
== 10-Oct-2017

1/1/1980 =? 1-JAN-1980
== true

sort [1/1/2017 5/10/1999 3-Jul-2017/5:41:40-2:00 1/1/1950 1/1/1980/2:2:2]
== [1-Jan-1950 1-Jan-1980/2:02:02 5-Oct-1999 1-Jan-2017 3-Jul-2017/5:41:40-02:00]
----


== Arytmetyka

Wspierane operacje matematyczne uwzględniają

* dodawanie lub odejmowanie wartości z każdego pola: wynik będzie znormalizowany.
* dodawanie lub odejmowanie wartości `integer!` z wartością `date!`: zinterpretowane jako liczba dni.
* dodawanie lub odejmowanie wartości `time!` z `date!`: doda/odejmie z/do czasu wartości `date!`.
* odejmowanie dwóch wartości: wynik będzie numer, ujemny lub dodatni, dni pomiędzy tymi dwoma wartościami `date!`.
* używając funkcji `difference` na dwóch wartościach `date!`: wynik będzie różnicą, ujemną lub dodatnią, wyrażoną jako wartość `time!` pomiędzy tymi dwoma wartościami `date!`

*Przykłady*

----
20-Feb-1980 + 50
== 10-Apr-1980

20-Feb-1980 + 3
== 23-Feb-1980

20-Feb-1980 - 25
== 26-Jan-1980

20-Feb-1980 + 100
== 30-May-1980

28-Feb-1980 + 20:30:45
== 28-Feb-1980/20:30:45

28-Feb-1980/8:30:00 + 20:30:45
== 29-Feb-1980/5:00:45

d: 20-Feb-1980
d/day: d/day + 50
== 10-Apr-1980

d: 20-Feb-1980
d/month: d/month + 5
== 20-Jul-1980

d: 28-Feb-1980/8:30:00
d/hour: d/hour + 48
== 1-Mar-1980/8:30:00

08/07/2017/10:45:00 - 20-Feb-1980/05:30:0
== 13653

difference 08/07/2017/10:45:00 20-Feb-1980/05:30:0
327677:15:00
----


== Pobieranie aktualnego czasu

Funkcja `now` zwróci aktualną date i czas systemu operacyjnego (włączając w to strefę casową). Wszystkie akcesory ścieżki są dostępne dla `now` jako refinement, z dodatkami:

* `/utc`: pobierz date w formacie `UTC`.

* `/precise`: pobierz date w bardziej precyzyjny sposób (1/60 dla Windows, mikrosekundy dla Unix)

*Przykłady*

----
now
== 8-Jul-2017/18:32:25+08:00

now/year
== 2017

now/hour
== 18

now/month
== 7

now/day
== 8

now/hour
== 18

now/zone
== 8:00:00

now/utc
== 8-Jul-2017/10:32:25
----


== Inne powiązane funkcje

=== Random

*Syntaktyka*

----
random <date>

<date> : a date! value
----

*Opis*

Zwraca losową date używając argumentu jako górny zakres. Jeżeli argument nie będzie miał ustawionych czasu lub strefy czasowej, wtedy wynikowa wartość `date!` też nie będzie ich miała.

*Przykłady*

----
random 09/07/2017
== 18-May-1972

random 09/07/2017
== 13-Aug-0981

random 09/07/2017/12:00:00+8
== 28-Feb-0341/17:57:12+04:00

random 09/07/2017/12:00:00+8
== 13-Dec-1062/5:09:12-00:30
----
