= Email! - typ danych
:toc:
:numbered:

== Streszczenie

Wartość `email!` umożliwia w bezpośredni sposób wyrażać adres e-mail, np: `foo@bar.net`

`Email!` jest członkiem danych typesetów (zbiór typów): `any-string!`, `series!`

== Tworzenie

Wartości `email!` mogą być stworzone przez dosłowną składnie, albo podczas uruchamiania przy użyciu konstruktora `make` albo konwertera `to`.

== Dosłowna składnia

Jeden albo więcej znaków, następnie symbol `@`, kończąc na 0 lub więcej dodatkowych znaków.

*Przykłady*

```
foo@bar.net
gregg@red-lang.org
g@
```

*Nieprawidłowe znaki*

`%` `(` `)` `:` `"`

== Tworzenie w czasie wykonywania

* `Make`
+
```red
>> f: make email! "foo"
== foo

>> type? f
== email!
```

* `To`
+
```red
>> b: to email! 'bar
== bar

>> type? b
== email!
```

== Akcesory ścieżki

Akcesory ścieżki dają możliwość w wygodny sposób odczyt albo zapis nazwy użytkownika albo nazwy hosta wartości `email!`.

=== /user

```red
>> e: me@me.net
== me@me.net

>> e/user
== "me"

>> e/user: "you"
== "you"

>> e
== you@me.net
```

=== /host

```red
>> e/host
== "me.net"

>> e/host: "red-lang.org"
== "red-lang.org"

>> e
== you@red-lang.org
```

== Porównania

Wszystkie operatory porównań mogą być użyte z `email!`: `=, ==, <>, >, <, >=, &lt;=, =?`. Ponadto, `min` i `max` tez są wspierane.

== Testing values

Użyj `email?`, aby sprawdzić czy wartość jest typu `email!`.

```red
>> email? foo@bar.net
== true
```

Użyj `type?`, aby zwrócić typ danych danej wartości.

```red
>> type? foo@bar.net
== email!
```

== Uprzednio zdefiniowane słowa

=== Funkcje

`email?`, `suffix?`, `to-email`
